# Generated by Django 6.0.3 on 2026-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Générique', max_length=100),
        ),
    ]
