# Generated by Django 6.0.3 on 2026-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Antalgique', 'Antalgique'), ('Antibiotique', 'Antibiotique'), ('Anti-inflammatoire', 'Anti-inflammatoire'), ('Antidiabétique', 'Antidiabétique'), ('Vitamines', 'Vitamines'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Antihistaminique', 'Antihistaminique'), ('Soin', 'Soin')], default='Antalgique', max_length=100),
        ),
    ]
